<?php

/** @var Magebit\Faq\Block\QuestionsList $block */
?>

<h1>Frequently Asked Questions</h1>
<?php foreach ($block->getQuestions() as $item): ?>

    <div id="accordion"
         data-mage-init='{"accordion":{
         "openedState": "active",
         "collapsible": true,
         "active": false,
         "multipleCollapsible": true}}'>
        <div class="question" data-role="collapsible">
            <div data-role="trigger">
                <span><?php echo $item->getData('question'); ?></span>
            </div>
        </div>
        <div class="answer" data-role="content"><?php echo $item->getData('answer') ?></div>
    </div>
<?php endforeach; ?>
