<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block View */

use Magento\Catalog\Block\Product\View;

?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) :?>
                <div class="field qty">
                    <div id="custom-qty" class="control" data-bind="scope: 'qty-counter'">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                        <script type="text/x-magento-init">
                            {
                                "#custom-qty": {
                                    "Magento_Ui/js/core/app": {
                                        "components": {
                                            "qty-counter": {
                                                "component": "qty-counter",
                                                "config": {
                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                }
                                            }
                                         }
                                    }
                                }
                            }
                        </script>
                    </div>
                    <div class="stock-container-custom">
                        <div class="instock-tick stock-item-info"></div>
                        <p class="stock-item-info in-stock">IN STOCK</p>
                        <p class="stock-item-info"><?= $block->escapeHtml($_product->getExtensionAttributes()->getStockItem()->getQty() . " items available");?></p>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
